---
services:
  postgres:
    image: ghcr.io/iglu-sh/postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: iglu
      POSTGRES_PASSWORD: iglu
      POSTGRES_DB: cache
    # Uncomment if you want to see all statements in postgres logs
    #command: ["postgres", "-c", "log_statement=all"]
    ports:
      - 5432:5432
    volumes:
      - ./dev/postgres:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=verysecret
  cache:
    image: ghcr.io/iglu-sh/iglu-cache:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: iglu
      POSTGRES_USER: iglu
      POSTGRES_HOST: postgres
      LOG_LEVEL: DEBUG
      LOG_JSON: false
      PROM_ENABLE: true
      CACHE_ROOT_DOMAIN: http://localhost
    ports:
      - 3000:3000
    volumes:
      - ./dev/repos:/tmp/repos
    depends_on:
      - postgres
      - redis