
/*
This endpoint is used to register a new builder node to this controller. It will send a registration request to this endpoint
with the following body:
{
  node_name: string, // The name of the node (randomly generated or set by the user)
  node_psk: string, // The pre-shared key for the node (generated by the node and hashed when we get it here so we can store it in the database without any trouble)
  node_address: string, // The address of the node (IP or domain)
  node_port: number, // The port of the node
  node_version: string, // The version of the node
  node_arch: string, // The architecture of the node (x86_64, arm64, etc.)
  node_os: string, // The operating system of the node (Linux, Darwin, etc.)
  node_max_jobs: number, // The maximum number of jobs the node can handle at once
}
*/
import type {NextRequest} from "next/server";
import type {nodeRegistrationRequest} from "@/types/api";

export async function POST(request:NextRequest){
    if(!request.headers.has("Authentication") || request.headers.get("Authentication") !== process.env.NODE_PSK){
        return new Response(JSON.stringify({message: "Unauthorized"}), {
            status: 401,
            headers: {
                "Content-Type": "application/json"
            }
        });
    }
    if(!request.body){
        return new Response(JSON.stringify({message: "Bad Request", cause: "No body provided"}), {
            status: 400,
            headers: {
                "Content-Type": "application/json"
            }
        });
    }
    const body = await request.json() as Record<string, unknown>;
    const mandatoryKeys = [
        "node_name",
        "node_psk",
        "node_address",
        "node_port",
        "node_version",
        "node_arch",
        "node_os",
        "node_max_jobs"
    ]
    for(const key of mandatoryKeys){
        if(!body.hasOwnProperty(key)){
            return new Response(JSON.stringify({message: "Bad Request", cause: `Missing key ${key} in body`}), {
                status: 400,
                headers: {
                    "Content-Type": "application/json"
                }
            });
        }
        if(typeof body[key] !== "string" && key !== "node_port" && key !== "node_max_jobs"){
            return new Response(JSON.stringify({message: "Bad Request", cause: `Key ${key} must be a string`}), {
                status: 400,
                headers: {
                    "Content-Type": "application/json"
                }
            });
        }
        if((key === "node_port" || key === "node_max_jobs") && typeof body[key] !== "number"){
            return new Response(JSON.stringify({message: "Bad Request", cause: `Key ${key} must be a number`}), {
                status: 400,
                headers: {
                    "Content-Type": "application/json"
                }
            });
        }
    }

    const registrationRequest:nodeRegistrationRequest = body as nodeRegistrationRequest;


}