import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {ThemeProvider} from "@/components/theme-provider";
import { Suspense} from "react";

const geistSans = localFont({
  src: '../../public/Geist-Regular.ttf',
  variable: "--font-geist-sans"
})

const geistMono = localFont({
  src: '../../public/GeistMono-Regular.ttf',
  variable: "--font-geist-mono",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
      >
          <Suspense>
              {children}
          </Suspense>
      </ThemeProvider>
      </body>
    </html>
  );
}
